version: 2

models:
  - name: Carbon_Capture_Categories
    description: Table of category types assigned to carbon capture facilities
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [facility_id, category]
    columns:
      - name: facility_id
        data_type: int64
        constraints:
          - type: foreign_key
            to: ref('Carbon_Capture_Facility')
            to_columns: [id]
        tests:
          - not_null
          - relationships:
              to: ref('Carbon_Capture_Facility')
              field: id

      - name: category
        data_type: string
        tests:
          - not_null

      - name: _data_source
        data_type: string

      - name: _load_time
        data_type: timestamp

    tests:
      - unique_combination_of_columns:
          combination_of_columns: [facility_id, category]
