version: 2

models:
  - name: Geo_References
    config:
      contract:
        enforced: true
    columns:
      - name: geo_id
        data_type: string
        constraints:
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: name
        data_type: string
      - name: capital
        data_type: string
      - name: _data_source
        data_type: string
      - name: _load_time
        data_type: timestamp